### PR TITLE
Hint version upgrade

### PR DESCRIPTION
**Pull request by NickSeagull**
Bumped the version for `hint` to allow using versions `>=0.6.0` and GHC 8

### CODE REVIEW

**Comment by cdupont** [comment]
Hi Nick! I merged your pull request. Thanks!
Can I ask what is your use case for Hint-server?

**Comment by NickSeagull** [comment]
Hi @cdupont, I'm trying to make an IDE or something like Python's Jupyter 😄

**Comment by cdupont** [comment]
Have you looked at https://hackage.haskell.org/package/ghc-mod?
Do you need to interpret code in your IDE (rather than compiling it)?

**Comment by NickSeagull** [comment]
Yes, I need to interpret it, the idea is to have an interactive environment for data exploration and other stuff

**Pull request merged**
